.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/inspectionProfiles/Project_Default.xml
- warn on glob imports
- Kotlin official code style weak warning for code analysis
- Set project to use Kotlin official code style for inspections
=> Add Android Studio code style and analysis configs

app/src/main/java/org/grapheneos/apps/client/App.kt, app/src/main/java/org/grapheneos/apps/client/service/KeepAppActive.kt, app/src/main/java/org/grapheneos/apps/client/service/SeamlessUpdaterJob.kt, app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/AppsListAdapter.kt, app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/ChannelPreferenceManager.kt, app/src/main/java/org/grapheneos/apps/client/utils/network/ApkDownloadHelper.kt, app/src/main/java/org/grapheneos/apps/client/utils/network/MetaDataHelper.kt, app/src/main/res/values/strings.xml
I don't know if there's a specific naming convention for the string names in the XML file since I see some like `app_name` and some camelcase or not.
=> Migrate some hardcoded strings to strings.xml

app/src/main/java/org/grapheneos/apps/client/item/PackageVariant.kt, app/src/main/java/org/grapheneos/apps/client/item/SeamlessUpdateResponse.kt, app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/AppsListAdapter.kt, app/src/main/java/org/grapheneos/apps/client/utils/network/FileVerifier.kt
=> Refactor some code to the Official Kotlin codestyle

app/build.gradle.kts, build.gradle.kts
There seems to have been some dependencies out of date.
Solves #51
=> Fix issue caused by gradle 7.1.0

app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/MainScreen.kt, app/src/main/res/menu/main_menu.xml, app/src/main/res/values/strings.xml
We need to be using the dependency metadata instead.
=> Remove "(Re)instal Google Play apps"

app/src/main/java/org/grapheneos/apps/client/App.kt
Left over code from "(Re)install Google Play apps"
=> Remove forceInstallGoogleApps

app/src/main/java/org/grapheneos/apps/client/ui/detailsScreen/res/layout/details_screen.xml
make Ui scrollable in case of longer description, release notes etc or in landscape mode
=> make details screen scrollable

app/src/main/java/org/grapheneos/apps/client/ui/detailsScreen/res/layout/item_dependency.xml, app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/res/layout/item_apps.xml, app/src/main/res/layout/updates_screen.xml, app/src/main/res/menu/mainscreen_bottom_nav.xml, app/src/main/res/values/strings.xml
=> Fix up some strings + use string resources

app/build.gradle.kts
=> Use stable channel of material

app/src/main/java/org/grapheneos/apps/client/ui/detailsScreen/res/layout/details_screen.xml
=> Fix description string res and typo in id label

app/src/main/java/org/grapheneos/apps/client/utils/View.kt
=> Fix illegibility of the error snackbar

app/src/main/java/org/grapheneos/apps/client/App.kt, app/src/main/java/org/grapheneos/apps/client/item/InstallStatus.kt, app/src/main/java/org/grapheneos/apps/client/item/PackageVariant.kt, app/src/main/java/org/grapheneos/apps/client/ui/detailsScreen/DetailsScreen.kt, app/src/main/java/org/grapheneos/apps/client/utils/PackageManagerHelper.kt, app/src/main/java/org/grapheneos/apps/client/utils/network/MetaDataHelper.kt, app/src/main/res/values/strings.xml
- Fix "uninstall" menu item for system apps.
- Fix "open button" navigating to details screen instead of opening app in some cases.
=> Ui improvement

app/src/main/AndroidManifest.xml, app/src/main/java/org/grapheneos/apps/client/App.kt, app/src/main/java/org/grapheneos/apps/client/item/InstallStatus.kt, app/src/main/java/org/grapheneos/apps/client/item/PackageInfo.kt, app/src/main/java/org/grapheneos/apps/client/item/PackageVariant.kt, app/src/main/java/org/grapheneos/apps/client/receiver/BootCompletedReceiver.kt, app/src/main/java/org/grapheneos/apps/client/service/SeamlessUpdaterJob.kt, app/src/main/java/org/grapheneos/apps/client/ui/detailsScreen/DetailsScreen.kt, app/src/main/java/org/grapheneos/apps/client/ui/detailsScreen/res/layout/details_screen.xml, app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/MainScreen.kt, app/src/main/java/org/grapheneos/apps/client/ui/search/SearchScreen.kt, app/src/main/java/org/grapheneos/apps/client/utils/PackageManagerHelper.kt, app/src/main/java/org/grapheneos/apps/client/utils/network/MetaDataHelper.kt, app/src/main/java/org/grapheneos/apps/client/utils/sharedPsfsMgr/JobPsfsMgr.kt, app/src/main/res/values/strings.xml
Closes
https://github.com/GrapheneOS/Apps/issues/126
https://github.com/GrapheneOS/Apps/issues/127
https://github.com/GrapheneOS/Apps/issues/148
=> bugfixes, cleanups, and support for disabled apps

app/src/main/java/org/grapheneos/apps/client/App.kt, app/src/main/java/org/grapheneos/apps/client/item/PackageInfo.kt, app/src/main/java/org/grapheneos/apps/client/item/PackageVariant.kt, app/src/main/java/org/grapheneos/apps/client/ui/detailsScreen/DependencyAdapter.kt, app/src/main/java/org/grapheneos/apps/client/ui/detailsScreen/DetailsScreen.kt, app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/AppsListAdapter.kt, app/src/main/java/org/grapheneos/apps/client/ui/search/SearchItemAdapter.kt, app/src/main/java/org/grapheneos/apps/client/uiItem/InstallablePackageInfo.kt, app/src/main/java/org/grapheneos/apps/client/utils/PackageManagerHelper.kt, app/src/main/java/org/grapheneos/apps/client/utils/network/ApkDownloadHelper.kt, app/src/main/java/org/grapheneos/apps/client/utils/network/DirConstant.kt, app/src/main/java/org/grapheneos/apps/client/utils/network/MetaDataHelper.kt
This PR has been made for ease of others reading the code and comparing it to the metadata structure. It also includes some simplifications to some functions if possible.
=> Refactor PackageVariant and PackageInfo data class to match metadata.json structure

app/build.gradle.kts, app/src/main/java/org/grapheneos/apps/client/ui/container/MainActivity.kt, app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/MainScreen.kt, app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/res/layout/main_screen.xml, app/src/main/res/menu/main_menu.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
Remove refresh button in favor of swipe to refresh gesture and menu, now correctly marking refresh state
=> improve refresh functionality

app/src/main/java/app/grapheneos/apps/core/InstallTask.kt
- enable confirmation UI in multi-package sessions, which is broken on Android before 13, but is now fixed on GrapheneOS 12.1
- add a missing null check in the privileged findPackage() method (splitSourceDirs is nullable on 12.1, but not on 13)
=> improve support for GrapheneOS 12.1 in privileged mode

app/src/main/java/app/grapheneos/apps/ApplicationImpl.kt, app/src/main/java/app/grapheneos/apps/autoupdate/AutoUpdateJob.kt, app/src/main/java/app/grapheneos/apps/core/Globals.kt
Closes https://github.com/GrapheneOS/Apps/issues/270
=> add a workaround for Android bug that breaks app initialization

app/src/main/java/app/grapheneos/apps/core/InstallTask.kt, app/src/main/java/app/grapheneos/apps/core/Repo.kt
Part of a changeset:
https://github.com/GrapheneOS/apps.grapheneos.org/pull/27
https://github.com/GrapheneOS/platform_frameworks_base/pull/314
https://github.com/GrapheneOS/platform_build/pull/31
=> add support for fs-verity

app/src/main/res/values/prefs.xml
=> Added "1 week" as an interval option

app/src/main/AndroidManifest.xml, app/src/main/java/app/grapheneos/apps/core/InstallStart.kt, app/src/main/java/app/grapheneos/apps/core/InstallTask.kt
Depends on https://github.com/GrapheneOS/platform_frameworks_base/pull/337
=> use installExistingPackage() for initial install of a system package

app/src/main/java/app/grapheneos/apps/autoupdate/AutoUpdatePrefs.kt, app/src/main/java/app/grapheneos/apps/core/Errors.kt, app/src/main/java/app/grapheneos/apps/core/InstallStart.kt, app/src/main/java/app/grapheneos/apps/core/InstallerSessions.kt, app/src/main/java/app/grapheneos/apps/core/PackageState.kt, app/src/main/java/app/grapheneos/apps/core/PkgInstallerStatusReceiver.kt, app/src/main/res/values/strings.xml
Depends on https://github.com/GrapheneOS/platform_frameworks_base/pull/340
=> improvements to auto-update functionality
