- app/src/main/java/org/grapheneos/apps/client/App.kt
- app/src/main/java/org/grapheneos/apps/client/item/DownloadCallBack.kt
- app/src/main/java/org/grapheneos/apps/client/utils/network/ApkDownloadHelper.kt
- app/src/main/res/values/strings.xml
Ui already prevent User from clicking download button/ calling download function over and over.
It's an extra layer of protection from mistakes that we as maintainer might make.
> avoid race condition  or multiple download of same file at same time

- app/build.gradle.kts
We won't target it yet until GrapheneOS has ported to Android 12L.
> Compile and use SDK 32 build tools

- app/src/main/java/org/grapheneos/apps/client/App.kt
- app/src/main/java/org/grapheneos/apps/client/service/SeamlessUpdaterJob.kt
Include the time since the notification is posted on background update results, download, and failed install notifications
> Show when the notification is posted on most cases

- app/src/main/java/org/grapheneos/apps/client/App.kt
- app/src/main/res/values/strings.xml
Include a more descriptive snackbar callback when attempting to tap the "Pending" button
> Implement callback for pending download/installs

- app/src/main/java/org/grapheneos/apps/client/App.kt
- app/src/main/java/org/grapheneos/apps/client/item/PackageVariant.kt
- app/src/main/java/org/grapheneos/apps/client/utils/network/MetaDataHelper.kt
Currently, it is not included in metadata whether an app uses original-package, thus hardwire the special case. 
Have the old package name as fallback to check for versionCode, and if the old package name has been updated and is a system app, update the install status of the newer package name.
> Correctly fetch for app version and updated version on new package name of PdfViewer when it's a system app

- app/src/main/java/org/grapheneos/apps/client/utils/network/MetaDataHelper.kt
Denying the Network permission on GrapheneOS no longer causes INTERNET
uses to throw SecurityException, so we don't need to check for it.
> Stop catching SecurityException in MetaDataHelper

- app/src/main/java/org/grapheneos/apps/client/utils/network/ApkDownloadHelper.kt
`verifyHash()` catches `NoSuchAlgorithmException` and rethrows it as
`GeneralSecurityException`, so it never actually throws
`NoSuchAlgorithmException` itself.
> Remove extraneous @Throws annotation

- app/src/main/java/org/grapheneos/apps/client/App.kt
- app/src/main/res/values/strings.xml
Multiple apps at a time being updated using update all button still causes Pending status, regardless of dependency status
> Clarify Pending Install Status message

- app/src/main/java/org/grapheneos/apps/client/utils/network/Constant.kt
- app/src/main/java/org/grapheneos/apps/client/utils/network/MetaDataHelper.kt
This doesn't change anything functionally but is more correct since the
metadata version and key version are decoupled.
> Use separate constant for signing key version

- app/src/main/java/org/grapheneos/apps/client/App.kt
This fixes a bug where the installing status is stalled due to wrongly using the old package name, when the newer one is received. Instead, always use the package name if it exists in the repository.
Let rPkgName be the received package name from broadcast instead, and oPkgName be its other equivalent based on samePackagesMap
> Bugfix: Always use the received package name when it's present at the repository data

- app/src/main/java/org/grapheneos/apps/client/ui/container/MainActivity.kt
Do not call `navigate()` on tapping search bar when it's already at the search screen, to avoid multiple back presses needed to go back at previous screen
> bugfix: Only trigger navigation to search screen when it's not from itself

- app/src/main/java/org/grapheneos/apps/client/App.kt
- app/src/main/java/org/grapheneos/apps/client/service/KeepAppActive.kt
- app/src/main/java/org/grapheneos/apps/client/ui/container/MainActivity.kt
- app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/AppsListAdapter.kt
- app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/MainScreen.kt
- app/src/main/res/values/strings.xml
This changeset includes 
-  disallowing refresh and download at the same time
- updating the button when downloaded from the app list screen, and
- improving view elements visibility when refresh is triggered
> Improve exposed refresh functionality and bugfixes

- app/src/main/java/org/grapheneos/apps/client/ui/mainScreen/res/layout/item_apps.xml
- app/src/main/java/org/grapheneos/apps/client/ui/search/res/layout/item_search.xml
This fixes a bug where doing refresh or changing filters can cause the position of the releaseTag TextView to shift by a random amount to the right as it is constrained to the appName TextView
Fixes #216
> Bugfix: Set appName TextView width to wrap_content

- app/build.gradle.kts
The update to bouncycastle 1.72 in a3bdc7f inadvertently added about 4 MiB of .properties files (as a result of bouncycastle's new Picnic and SIKE implementations) to optimized release builds, increasing their size by ~168%. Since we're not using bouncycastle for these algorithms, exclude the extraneous files to reduce app size.
> Exclude extraneous bouncycastle .properties files

- app/src/main/java/app/grapheneos/apps/util/BundleUtils.kt
This sometimes led to ClassNotFoundException after Bundle was deserialized, eg when app process was recreated and state from previous process instance had non-framework objects stored in a Bundle.
> bugfix: missing class loader override for deserialized Bundles

- app/src/main/res/layout/package_list_item.xml
The layout should have a maximum padding of 8dp between cards. Reference: https://m3.material.io/components/cards/specs#9abbced9-d5d3-4893-9a67-031825205f06
It's expected that this card will be included in views such as a dynamic list. Using a 4dp vertical margin results in an 8dp margin between the cards.
Fixes https://github.com/GrapheneOS/Apps/issues/289
> fix(layout): use 8dp max padding between cards

- app/src/main/AndroidManifest.xml
- app/src/main/java/app/grapheneos/apps/ApplicationImpl.kt
- app/src/main/java/app/grapheneos/apps/Notifications.kt
- app/src/main/java/app/grapheneos/apps/RpcProvider.kt
- app/src/main/java/app/grapheneos/apps/autoupdate/AutoUpdateJob.kt
- app/src/main/java/app/grapheneos/apps/autoupdate/AutoUpdatePrefs.kt
- app/src/main/java/app/grapheneos/apps/autoupdate/UpdateCheckJob.kt
- app/src/main/java/app/grapheneos/apps/core/InstallStart.kt
- app/src/main/java/app/grapheneos/apps/core/InstallTask.kt
- app/src/main/java/app/grapheneos/apps/core/PackageState.kt
- app/src/main/java/app/grapheneos/apps/core/PackageStates.kt
- app/src/main/java/app/grapheneos/apps/core/PkgInstallerStatusReceiver.kt
- app/src/main/java/app/grapheneos/apps/core/RepoRetriever.kt
- app/src/main/java/app/grapheneos/apps/ui/UpdatesScreen.kt
- app/src/main/java/app/grapheneos/apps/util/HttpUtils.kt
- app/src/main/res/layout/details_screen.xml
- app/src/main/res/values/strings.xml
- split it up into 2 jobs: update check job and auto update job (see comment in
AutoUpdatePrefs.setupJobs())
- refactor code in InstallStart to support this new split setup
- make sure that "Apps are up-to-date" notification is shown even if our process was killed while
the OS was installing submitted app updates by moving the code that shows this notification into the
package install status receiver (if our process was killed, it'll be spawned again by the OS to
instantiate this receiver)
> reimplement auto-update functionality 

- app/src/main/java/app/grapheneos/apps/core/Globals.kt
- app/src/main/java/app/grapheneos/apps/core/PackageState.kt
Before "grapheneos.package_update_preserves_package_enabled_setting" system feature, update of disabled package made it re-enabled.
Android 14 should add an API for this, but it hasn't stabilized yet.
Closes https://github.com/GrapheneOS/Apps/issues/266
> support updating disabled packages on compatible OS versions

- app/src/main/res/layout/package_list_item.xml
- app/src/main/res/values/strings.xml
* remove label of app icon as it's not nessesary and slows down navigation by TalkBack hearing it repetitively on each item.
* Workarround: mark `com.google.android.material.chip.Chip` as uncheckable.
Note that according to Material Design documentation, chip is wrongly applied here:
> Chips are compact elements that represent an input, attribute, or action.
Here it's impossible to do input or action, because in order to change the current channel we do it by other way/screen.
> Accessibility improvements

- app/src/main/java/app/grapheneos/apps/core/Repo.kt
`json` variable references the RPackageContainer object, not RPackage object.
> fix static deps for package variants
